### ISSUE TITLE
mhc_class filter misses some patterns

### ISSUE THREAD

**Issue by arahuja** [hammerlab/pepdata#34]
The old MHC filter on `tcell_compact`

```
mhc1_pattern = 'Class I,|HLA-[A-C](?:[0-9]|\*)'
```

misses `HLA-class I` and similarly `mhc2_pattern` misses `HLA-class II` which occur fairly frequently.

**Comment by iskandr** [comment]
Fixed using `iedb.alleles` module to check allele classes.
